import { z } from 'zod';
import {
  ConditionIdSchema,
  IsoCalendarDateStringSchema,
  IsoDateTimeStringSchema,
  MarketIdSchema,
  MixedDateTimeStringSchema,
  PaginationCursorSchema,
  TickSizeValueSchema,
  TokenIdSchema,
} from '../shared';
import {
  CategoryReferenceSchema,
  ClobRewardsSchema,
  EventReferenceSchema,
  FeeScheduleSchema,
  ImageOptimizationSchema,
  InternalUserSchema,
  RelatedMarketSchema,
  TagReferenceSchema,
} from './common';

const StringPairSchema = z.tuple([z.string(), z.string()]);
const TokenIdPairValueSchema = z.tuple([TokenIdSchema, TokenIdSchema]);

const OutcomePairSchema = z
  .union([z.string().transform((val) => JSON.parse(val)), StringPairSchema])
  .pipe(StringPairSchema);

const OutcomePricePairSchema = z
  .union([z.string().transform((val) => JSON.parse(val)), StringPairSchema])
  .pipe(StringPairSchema);

const TokenIdPairSchema = z
  .union([
    z.string().transform((val) => JSON.parse(val)),
    z.tuple([z.string(), z.string()]),
  ])
  .pipe(TokenIdPairValueSchema);

export const MarketSchema = z
  .looseObject({
    id: MarketIdSchema,
    question: z.string().nullish(),
    conditionId: ConditionIdSchema,
    slug: z.string().nullish(),
    twitterCardImage: z.string().nullish(),
    resolutionSource: z.string().nullish(),
    endDate: IsoDateTimeStringSchema.nullish(),
    category: z.string().nullish(),
    ammType: z.string().nullish(),
    liquidity: z.string().nullish(),
    sponsorName: z.string().nullish(),
    sponsorImage: z.string().nullish(),
    startDate: IsoDateTimeStringSchema.nullish(),
    xAxisValue: z.string().nullish(),
    yAxisValue: z.string().nullish(),
    denominationToken: z.string().nullish(),
    fee: z.string().nullish(),
    image: z.string().nullish(),
    icon: z.string().nullish(),
    lowerBound: z.string().nullish(),
    upperBound: z.string().nullish(),
    description: z.string().nullish(),
    outcomes: OutcomePairSchema.nullish(),
    outcomePrices: OutcomePricePairSchema.nullish(),
    volume: z.string().nullish(),
    active: z.boolean().nullish(),
    marketType: z.string().nullish(),
    formatType: z.string().nullish(),
    lowerBoundDate: IsoCalendarDateStringSchema.nullish(),
    upperBoundDate: IsoCalendarDateStringSchema.nullish(),
    closed: z.boolean().nullish(),
    marketMakerAddress: z.string(),
    createdBy: z.number().int().nullish(),
    updatedBy: z.number().int().nullish(),
    createdAt: IsoDateTimeStringSchema.nullish(),
    updatedAt: IsoDateTimeStringSchema.nullish(),
    closedTime: IsoDateTimeStringSchema.nullish(),
    wideFormat: z.boolean().nullish(),
    new: z.boolean().nullish(),
    sentDiscord: z.boolean().nullish(),
    mailchimpTag: z.string().nullish(),
    featured: z.boolean().nullish(),
    submitted_by: z.string().nullish(),
    subcategory: z.string().nullish(),
    categoryMailchimpTag: z.string().nullish(),
    twitterCardLocation: z.string().nullish(),
    twitterCardLastRefreshed: IsoDateTimeStringSchema.nullish(),
    twitterCardLastValidated: IsoDateTimeStringSchema.nullish(),
    archived: z.boolean().nullish(),
    resolvedBy: z.string().nullish(),
    restricted: z.boolean().nullish(),
    marketGroup: z.number().int().nullish(),
    groupItemTitle: z.string().nullish(),
    groupItemThreshold: z.string().nullish(),
    questionID: z.string().nullish(),
    umaEndDate: MixedDateTimeStringSchema.nullish(),
    enableOrderBook: z.boolean().nullish(),
    orderPriceMinTickSize: TickSizeValueSchema.nullish(),
    orderMinSize: z.number().nullish(),
    umaResolutionStatus: z.string().nullish(),
    curationOrder: z.number().int().nullish(),
    volumeNum: z.number().nullish(),
    liquidityNum: z.number().nullish(),
    endDateIso: IsoCalendarDateStringSchema.nullish(),
    startDateIso: IsoCalendarDateStringSchema.nullish(),
    umaEndDateIso: IsoCalendarDateStringSchema.nullish(),
    hasReviewedDates: z.boolean().nullish(),
    readyForCron: z.boolean().nullish(),
    commentsEnabled: z.boolean().nullish(),
    volume24hr: z.number().nullish(),
    volume1wk: z.number().nullish(),
    volume1mo: z.number().nullish(),
    volume1yr: z.number().nullish(),
    gameStartTime: IsoDateTimeStringSchema.nullish(),
    secondsDelay: z.number().int().nullish(),
    clobTokenIds: TokenIdPairSchema.nullish(),
    disqusThread: z.string().nullish(),
    shortOutcomes: z.string().nullish(),
    teamAID: z.string().nullish(),
    teamBID: z.string().nullish(),
    umaBond: z.string().nullish(),
    umaReward: z.string().nullish(),
    fpmmLive: z.boolean().nullish(),
    volume24hrAmm: z.number().nullish(),
    volume1wkAmm: z.number().nullish(),
    volume1moAmm: z.number().nullish(),
    volume1yrAmm: z.number().nullish(),
    volume24hrClob: z.number().nullish(),
    volume1wkClob: z.number().nullish(),
    volume1moClob: z.number().nullish(),
    volume1yrClob: z.number().nullish(),
    volumeAmm: z.number().nullish(),
    volumeClob: z.number().nullish(),
    liquidityAmm: z.number().nullish(),
    liquidityClob: z.number().nullish(),
    makerBaseFee: z.number().int().nullish(),
    takerBaseFee: z.number().int().nullish(),
    customLiveness: z.number().int().nullish(),
    acceptingOrders: z.boolean().nullish(),
    negRisk: z.boolean().nullish(),
    negRiskMarketID: z.string().nullish(),
    negRiskRequestID: z.string().nullish(),
    notificationsEnabled: z.boolean().nullish(),
    score: z.number().int().nullish(),
    imageOptimized: ImageOptimizationSchema.nullish(),
    iconOptimized: ImageOptimizationSchema.nullish(),
    events: z.array(EventReferenceSchema).nullish(),
    categories: z.array(CategoryReferenceSchema).nullish(),
    markets: z.array(RelatedMarketSchema).nullish(),
    creator: z.string().nullish(),
    ready: z.boolean().nullish(),
    funded: z.boolean().nullish(),
    pastSlugs: z.string().nullish(),
    readyTimestamp: IsoDateTimeStringSchema.nullish(),
    fundedTimestamp: IsoDateTimeStringSchema.nullish(),
    acceptingOrdersTimestamp: IsoDateTimeStringSchema.nullish(),
    tags: z.array(TagReferenceSchema).nullish(),
    cyom: z.boolean().nullish(),
    competitive: z.number().nullish(),
    pagerDutyNotificationEnabled: z.boolean().nullish(),
    approved: z.boolean().nullish(),
    clobRewards: z.array(ClobRewardsSchema).nullish(),
    rewardsMinSize: z.number().nullish(),
    rewardsMaxSpread: z.number().nullish(),
    spread: z.number().nullish(),
    automaticallyResolved: z.boolean().nullish(),
    oneDayPriceChange: z.number().nullish(),
    oneHourPriceChange: z.number().nullish(),
    oneWeekPriceChange: z.number().nullish(),
    oneMonthPriceChange: z.number().nullish(),
    oneYearPriceChange: z.number().nullish(),
    lastTradePrice: z.number().nullish(),
    bestBid: z.number().nullish(),
    bestAsk: z.number().nullish(),
    automaticallyActive: z.boolean().nullish(),
    clearBookOnStart: z.boolean().nullish(),
    chartColor: z.string().nullish(),
    seriesColor: z.string().nullish(),
    showGmpSeries: z.boolean().nullish(),
    showGmpOutcome: z.boolean().nullish(),
    manualActivation: z.boolean().nullish(),
    negRiskOther: z.boolean().nullish(),
    gameId: z.string().nullish(),
    groupItemRange: z.string().nullish(),
    sportsMarketType: z.string().nullish(),
    line: z.number().nullish(),
    umaResolutionStatuses: z.string().nullish(),
    pendingDeployment: z.boolean().nullish(),
    deploying: z.boolean().nullish(),
    deployingTimestamp: IsoDateTimeStringSchema.nullish(),
    scheduledDeploymentTimestamp: IsoDateTimeStringSchema.nullish(),
    rfqEnabled: z.boolean().nullish(),
    eventStartTime: IsoDateTimeStringSchema.nullish(),
    internalUsers: z.array(InternalUserSchema).nullish(),
    holdingRewardsEnabled: z.boolean().nullish(),
    feesEnabled: z.boolean().nullish(),
    requiresTranslation: z.boolean().nullish(),
    makerRebatesFeeShareBps: z.number().int().nullish(),
    feeRate: z.number().nullish(),
    feeExponent: z.number().nullish(),
    feeType: z.string().nullish(),
    feeSchedule: FeeScheduleSchema.nullish(),
  })
  .transform(
    ({
      acceptingOrdersTimestamp,
      deployingTimestamp,
      endDateIso,
      fundedTimestamp,
      readyTimestamp,
      scheduledDeploymentTimestamp,
      startDateIso,
      submitted_by,
      umaEndDateIso,
      ...rest
    }) => ({
      ...rest,
      acceptingOrdersAt: acceptingOrdersTimestamp,
      deployingAt: deployingTimestamp,
      endDateOnly: endDateIso,
      fundedAt: fundedTimestamp,
      readyAt: readyTimestamp,
      scheduledDeploymentAt: scheduledDeploymentTimestamp,
      startDateOnly: startDateIso,
      submittedBy: submitted_by,
      umaEndDateOnly: umaEndDateIso,
    }),
  );

export const ListMarketsResponseSchema = z.array(MarketSchema);
export const ListMarketsKeysetResponseSchema = z
  .object({
    markets: z.array(MarketSchema),
    next_cursor: PaginationCursorSchema.optional(),
  })
  .transform(({ markets, next_cursor }) => ({
    items: markets,
    nextCursor: next_cursor,
  }));
export const FetchMarketTagsResponseSchema = z.array(TagReferenceSchema);

export type Market = z.infer<typeof MarketSchema>;
export type ListMarketsResponse = z.infer<typeof ListMarketsResponseSchema>;
export type ListMarketsKeysetResponse = z.infer<
  typeof ListMarketsKeysetResponseSchema
>;
export type FetchMarketTagsResponse = z.infer<
  typeof FetchMarketTagsResponseSchema
>;
