name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  test:
    name: Tests
    needs: verify
    uses: ./.github/workflows/tests.yml

  integration-tests:
    name: Integration Tests
    needs: verify
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  release:
    name: Publish Canary
    runs-on: ubuntu-latest
    needs:
      - verify
      - test
      # Temporarily do not block publishing on integration tests while checks are blocked by a BE bug.
      # - integration-tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Repository
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Version Packages For Canary
        run: pnpm version:canary

      - name: Publish Canary Packages
        run: pnpm release:canary
